Fix/add one line quotation display
zdzislawbela/calculator pull request #4
Opened 2020-12-19 20:58 UTC by zdzislawbela

2020-12-19 22:55 UTC, raqso requested changes

2020-12-19 22:55 UTC, raqso commented on events/handlePressedButton.js
> +        if (currentValue.slice(currentValue.length-1,currentValue.length) === ")") {
extarct to const

2020-12-19 22:55 UTC, raqso commented on events/handlePressedButton.js
> +        parseInt(currentValue.slice(currentValue.indexOf(".")+1, currentValue.length)) === 0
:hankey:

2020-12-19 22:55 UTC, raqso commented on events/handlePressedButton.js
> +    savedValues.forEach((savedValue) => {
Put into map

2020-12-19 22:55 UTC, raqso commented on events/handlePressedButton.js
> +    document.querySelector('.display').appendChild(newDisplayRow);
Extract to function

2020-12-19 22:55 UTC, raqso commented on src/calculator/keyboard/keyboard.css
> +/* .operator
🗑️

2020-12-19 22:55 UTC, raqso commented on src/calculator/keyboard/keyboard.js
> +    const ButtonClass = "button";
```suggestion
    const buttonClass = "button";
```

2020-12-19 22:55 UTC, raqso commented on src/calculator/keyboard/keyboard.js
>      const buttons = [
Extract to a enum

2020-12-19 22:55 UTC, raqso commented on src/main.js
> +//import {setKeyClassInterval} from '../events/displayEvents.js';
🗑️

2020-12-19 22:55 UTC, raqso commented on src/main.js
> +    //setInterval(setKeyClassInterval, 3000);
🗑️

2020-12-19 22:55 UTC, raqso commented on src/main.js
>  export default () => {
Name the function

2021-01-13 20:15 UTC, zdzislawbela commented on events/eventHandlers_old.js
> +    //const lastRowVaule = "3.33+1.223";
```suggestion
    //const lastRowVaule = "3.33+1.223";
    
```

2021-01-13 23:52 UTC, zdzislawbela commented on events/displayEvents.js
> +        savedDisplayValues.forEach((savedValue) => {
but I need a string not an array

2021-01-14 16:43 UTC, merged